const API_URL="";
const preAccount=[
    {
        id:'ex1',
        type:'admin',
        nameLogin:'admin', 
        email:'admin@SpeechGrammarList.com'
    },
    {
        id:'ex1',
        type:'user',
        nameLogin:'user',  
        email:'admin@SpeechGrammarList.com'
    },
]
const preData = [{
    ID: "1",
    type: "Stupffed animal",
    name: "STRIPED BUFFALO SHIRT",
    img: "image/gauTrauAoKe1.jpg",
    img2: "image/gauTrauAoKe2.jpg",
    img3: "image/gauTrauAoKe3.jpg",
    img4: "image/gauTrauAoKe5.jpg",
    // img4:"image./gauTrauAoke4.jpg",
    price: 170000,
    price2: 250000,
    price3: 340000,
    size1: "1m",
    size2: "1m3",
    size3: "50cm",
    status: "stocking",
    comment: "Bong Ao Ke buffalo is currently sold at the store with 2 sizes 40cm, 50cm and 3 colors blue, pink,</br> orange, priced from only 190,000 VND",
    comment2: "Cotton Buffalo Plaid"
},
{
    ID: "2",
    type: "Stupffed animal",
    name: "BUFFALO NECK PILLOWS",
    img: "image/gauCoTrau.jpg",
    img2: "image/gauCoTrau2.jpg",
    img3: "image/gauCoTrau3.jpg",
    // img3: "gauCoTrau4.jpg",
    // img3: "gauCoTrau5.jpg",
    price: 150000,
    price2: 200000,
    price3: 30000,
    size1: "1m2",
    size3: "1m5",
    size3: "1m",
    status: "stocking",
    comment: "Co Trau pillows are currently sold at stores with 3 colors: blue, red, and yellow, priced at only 150,000 VND",
    comment2: "Buffalo Neck Pillows - Red"
},
{
    ID: "3",
    type: "Stupffed animal",
    name: "Dinosaur teddy bear",
    img: "image/khungLong1.jpg",
    img2: "image/khungLong2.jpg",
    img3: "image/khungLong3.jpg",
    img3: "image/khungLong4.jpg",
    img3: "image/khungLong5.jpg",
    price: 390000,
    price2: 550000,
    price3: 585000,
    size1: "1m",
    size2: "1m3",
    size3: "50cm",
    status: "stocking",
    status2: "stocking",
    status3: "out of stock",
    comment: "Fluffy Dinosaur Teddy Bear",
    comment2: "Cute pink dinosaur teddy bear"
},
{
    ID: "4",
    type: "Teddy",
    name: "TEDDY BEAR CREAM CAKE",
    img: "image/teddy.jpg",
    img2: "image/teddy4.jpg",
    img3: "image/teddy5.jpg",
    img4: "image/teddy4.jpg",
    img5: "image/teddy5.jpg",
    price: 490000,
    price2: 750000,
    price3: 985000,
    size1: "1m",
    size2: "1m3",
    size3: "1m6",
    status: "stocking",
    status2: "stocking",
    status3: "out of stock"
},
{
    ID: "5",
    type: "Teddy",
    name: "TEDDY ANGEL PINK",
    img: "image/teddyHong1.jpg",
    img2: "image/teddyHong2.jpg",
    img3: "image/teddyHong3.jpg",
    img4: "image/teddyHong4.jpg",
    img5: "image/teddyHong5.jpg",
    price: 290000,
    price2: 550000,
    price3: 585000,
    size1: "1m",
    size2: "1m3",
    size3: "1m6",
    status: "stocking",
    status2: "stocking",
    status3: "out of stock"
},
{
    ID: "6",
    type: "Cat",
    name: "cute cat",
    img: "image/meo2.jpg",
    img2: "image/meo4.jpg",
    img3: "image/meo5.jpg",
    img4: "image/meo3.jpg",
    img5: "image/meo2.jpg",
    price: 290000,
    price2: 550000,
    price3: 585000,
    size1: "1m",
    size2: "1m3",
    size3: "50cm",
    status: "stocking",
    status2: "stocking",
    status3: "out of stock"
},
{
    ID: "7",
    type: "Doremon",
    name: "Cute doremon",
    img: "image/doremon1.jpg",
    img2: "image/bigDoremon.jpg",
    img3: "image/bigDoremon1.jpg",
    img4: "image/doremon1.jpg",
    img5: "image/doremonDetail.jpg",
    price: 290000,
    price2: 550000,
    price3: 585000,
    size1: "1m",
    size2: "1m3",
    size3: "50cm",
    status: "stocking",
    status2: "stocking",
    status3: "out of stock"
},

]
